Adds flat tree combiner app that acts like a poor-persons hadd for nuisance flat trees while remembering to scale down fScaleFactor by NInputTrees. Will work with files of differing numbers of events, but should only really use to spread out large flat tree generation runs to a cluster and then recombine them to a single file.

diff --git a/event_gen/nuis_genev_neut b/event_gen/nuis_genev_neut
--- a/event_gen/nuis_genev_neut
+++ b/event_gen/nuis_genev_neut
@@ -93,7 +93,19 @@ while [[ ${#} -gt 0 ]]; do
       fi
 
       MDLQE="$2"
-      echo "[OPT]: Writing to file: ${MDLQE}"
+      echo "[OPT]: Using MDLQE = ${MDLQE}"
+      shift # past argument
+      ;;
+
+      --MAQE)
+
+      if [[ ${#} -lt 2 ]]; then
+        echo "[ERROR]: ${1} expected a value."
+        exit 1
+      fi
+
+      MAQE="$2"
+      echo "[OPT]: Attempting to generate with MAQE = ${MAQE}"
       shift # past argument
       ;;
 
@@ -178,7 +190,9 @@ if [ -z {$FLUX_FILE} ] || [ -z {$FLUX_HIST} ]; then
 fi
 
 FLUX_FILE_NAME=${FLUX_FILE##*/}
-cp ${FLUX_FILE} ./
+if [ ! -e ./${FLUX_FILE} ]; then
+  cp ${FLUX_FILE} ./
+fi
 
 if [ -z ${NEVENTS} ] ; then
    echo "Please pass an integer number of events to run with the -n flag."
