Significant work on the nuis-valid CLI and associated scripts. Removes the old contents of the validation folder which haven't been used in many moons. Adds NuWro interface for nuis-gen, various small tweaks/fixes to nuis gen in general as they have come up durng validation.

diff --git a/CLI/nuis-flux b/CLI/nuis-flux
--- a/CLI/nuis-flux
+++ b/CLI/nuis-flux
@@ -12,9 +12,10 @@ function nuis_flux_help {
   echo -e "\tCommands:"
   echo -e "\t  help                                 : Display this message"
   echo -e "\t  list-experiments                     : List all implemented experiment names"
+  echo -e "\t  range <rootfile,histname>            : Say the X axis range of the passed histogram"
   echo -e "\tOptions:"
-  echo -e "\t  -p|--probe <numu|nue|numubar|nuebar> : Defaults to numu"
-  echo -e "\t  -m|--beam-mode <nu|nubar>            : Defaults to nu"
+  echo -e "\t  -P|--probe <numu|nue|numubar|nuebar> : Defaults to numu"
+  echo -e "\t  -M|--beam-mode <nu|nubar>            : Defaults to nu"
   echo -e "\nExample: ${NUIS_BREADCRUMBS} MINERvA -p numubar -m nubar\n"
 }
 
@@ -51,6 +52,27 @@ case $KEYARG in
     exit 0
     ;;
 
+  range)
+
+    if [[ ${#} -lt 1 ]]; then
+      echo "[ERROR]: ${KEYARG} expected a value."
+      exit 1
+    fi
+
+    RANGE_FLUX_DESCRIPTOR=${1}
+
+    OLDIFS=${IFS}
+    IFS=","
+    set -- ${RANGE_FLUX_DESCRIPTOR}
+    IFS=${OLDIFS}
+
+    RANGE_FLUX_FILE=${1}
+    RANGE_FLUX_HIST=${2}
+
+    nuishistrange ${RANGE_FLUX_FILE} ${RANGE_FLUX_HIST}
+    exit 0
+    ;;
+
   help)
     nuis_flux_help
     exit 0
@@ -70,7 +92,7 @@ while [[ ${#} -gt 0 ]]; do
   key="$1"
   case $key in
 
-  -p|--probe)
+  -P|--probe)
 
       if [[ ${#} -lt 2 ]]; then
         echo "[ERROR]: ${1} expected a value."
@@ -81,7 +103,7 @@ while [[ ${#} -gt 0 ]]; do
       shift # past argument
       ;;
 
-  -m|--beam-mode)
+  -M|--beam-mode)
 
       if [[ ${#} -lt 2 ]]; then
         echo "[ERROR]: ${1} expected a value."
@@ -96,7 +118,7 @@ while [[ ${#} -gt 0 ]]; do
 
       echo -e "Experimental Fluxes Available:"
       echo -e "    ANL_77 (ANL)"
-      echo -e "    ArgoNeut"
+      echo -e "    ArgoNeuT"
       echo -e "    BEBC"
       echo -e "    BNL_81"
       echo -e "    BNL_86"
@@ -149,7 +171,7 @@ case $EXPERIMENT in
       exit 0
     fi
     ;;
-  ArgoNeut)
+  ArgoNeuT)
     if [ "${PROBE}" == "numu" ] && [ "${BEAMMODE}" == "nu" ]; then
       echo "${NUISANCE}/data/flux/ArgoNeut_numu_flux.root,numu"
       exit 0
diff --git a/CLI/nuis-gen b/CLI/nuis-gen
--- a/CLI/nuis-gen
+++ b/CLI/nuis-gen
@@ -8,18 +8,21 @@ echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): ${COMMAND} Arguments(${#}):" "${@}
 fi
 
 function nuis_gen_help {
-  echo "Run like: ${NUIS_BREADCRUMBS} -t <T> [-f <FF,FH>|-e <E> [ -p <P> -m <M>]] -n <N> [options]"
+  echo "Run like: ${NUIS_BREADCRUMBS} -t <T> [-f <FF,FH>|-E <E> [ -P <P> -M <M>]] -n <N> [options]"
   echo -e "\tRequired:"
-  echo -e "\t-t|--target <T>                      : Set target descriptor, e.g. <T>=\"CH\""
-  echo -e "\t-n|--nevents <N>                     : Generate <N> events"
-  echo -e "\t-f|--flux <file.root,histoname>      : Use neutrino energy shape from described histogram"
-  echo -e "\t--flux-MeV                           : Interpret flux histogram as being in MeV"
+  echo -e "\t  -t|--target <T>                      : Set target descriptor, e.g. <T>=\"CH\""
+  echo -e "\t  -n|--nevents <N>                     : Generate <N> events"
+  echo -e "\t  -f|--flux <file.root,histoname>      : Use neutrino energy shape from described histogram"
+  echo -e "\t  --flux-MeV                           : Interpret flux histogram as being in MeV"
   echo -e "\tOR"
-  echo -e "\t-e|--experiment                      : Passed to \'nuis flux\' to specify known experimental flux"
-  echo -e "\t-m|--beam-mode <nu|nubar>            : Passed to \'nuis flux\' to specify known flux beam mode"
+  echo -e "\t  -E|--experiment                      : Passed to \'nuis flux\' to specify known experimental flux"
+  echo -e "\t  -M|--beam-mode <nu|nubar>            : Passed to \'nuis flux\' to specify known flux beam mode"
   echo -e "\tOptional:"
-  echo -e "\t-p|--probe <numu|nue|numubar|nuebar> : Set probe particle. If -e is used, this is also passed to \'nuis flux\'."
-  echo -e "\t-o|--output-file <output.root>       : defaults to NEUT.<probepdg>.<flux_file>.<flux_hist>.<seed>.neutvect.root"
+  echo -e "\t  -P|--probe <numu|nue|numubar|nuebar> : Set probe particle. If -e is used, this is also passed to \'nuis flux\'."
+  echo -e "\t  -o|--output-file <output.root>       : defaults to <GENERATOR>.<probe>.<flux_file>.<flux_hist>.<seed>.evts.root"
+  echo -e "\t  --seed <int>                         : Integer to use as random seed. Defaults to \${RANDOM}"
+  echo -e "\t  --quiet                              : Pipe gevgen output to /dev/null"
+  echo -e ""
 }
 
 if [ "${#}" -lt 1 ] || [ "${1::1}" == "-" ]; then
@@ -68,14 +71,32 @@ BEAM_MODE="nu"
 FLUX_DESCRIPTOR=""
 FLUX_MeV="off"
 
+SEED=
+QUIET=FALSE
+
 FORWARDED_ARGS=()
+
+# If the first arg after the VERB is another sub command, then just instant forward it and all other options
+if [[ ${#} -gt 0 ]] && [ "${1::1}" != "-" ]; then
+
+  if [ "${1}" == "help" ]; then
+    nuis_gen_help
+    NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
+      ${COMMAND}-${VERB} help
+    exit 0
+  fi
+
+  NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
+    ${COMMAND}-${VERB} "${@}"
+  exit $?
+fi
 
 while [[ ${#} -gt 0 ]]; do
 
   key="$1"
   case $key in
 
-    -p|--probe)
+    -P|--probe)
 
       if [[ ${#} -lt 2 ]]; then
         echo "[ERROR]: ${NUIS_BREADCRUMBS} -- ${1} expected a value."
@@ -117,7 +138,7 @@ while [[ ${#} -gt 0 ]]; do
       FLUX_MeV="on"
       ;;
 
-    -e|--experiment)
+    -E|--experiment)
 
       if [[ ${#} -lt 2 ]]; then
         echo "[ERROR]: ${NUIS_BREADCRUMBS} -- ${1} expected a value."
@@ -129,7 +150,7 @@ while [[ ${#} -gt 0 ]]; do
       shift # past argument
       ;;
 
-    -m|--beam-mode)
+    -M|--beam-mode)
 
       if [[ ${#} -lt 2 ]]; then
         echo "[ERROR]: ${NUIS_BREADCRUMBS} -- ${1} expected a value."
@@ -165,36 +186,67 @@ while [[ ${#} -gt 0 ]]; do
       shift # past argument
       ;;
 
-    help)
-      nuis_gen_help
-      ${COMMAND}-${VERB} help
-      exit 0
+    --seed)
+
+      if [[ ${#} -lt 2 ]]; then
+        echo "[ERROR]: ${NUIS_BREADCRUMBS} -- ${1} expected a value."
+        exit 1
+      fi
+
+      SEED="$2"
+      echo "[OPT]: ${NUIS_BREADCRUMBS} -- Using ${SEED} as random seed."
+      shift # past argument
       ;;
 
+  --quiet)
+
+      QUIET=TRUE
+      ;;
 
     *) # unknown option
-      FORWARDED_ARGS+="${key}"
+      FORWARDED_ARGS+=("${key}")
       ;;
   esac
   shift
 done
 
-if [ -z "${TARGET_NAME}" ]; then
+case ${PROBE} in
+  numu)
+    PROBE_PDG="14"
+    ;;
+  numubar)
+    PROBE_PDG="-14"
+    ;;
+  nue)
+    PROBE_PDG="12"
+    ;;
+  nuebar)
+    PROBE_PDG="-12"
+    ;;
+  *)
+    echo "[ERROR]: ${NUIS_BREADCRUMBS} -- Invalid probe descriptor passed: ${PROBE}"
+    nuis_gen_help
+    ${COMMAND}-${VERB} help
+    exit 1
+esac
+
+#The user might want to manually set the target for NuWro with -p arguments
+if [ "${VERB}" != "NuWro" ] && [ -z "${TARGET_NAME}" ]; then
   echo "[ERROR]: ${NUIS_BREADCRUMBS} -- Please pass target materical descriptor, e.g. CH"
   exit 1
 fi
 
 if [ -z "${NEVENTS}" ]; then
-  echo "Please pass a number of events to generate with the -n flag."
+  echo "[ERROR]: ${NUIS_BREADCRUMBS} -- Please pass a number of events to generate with the -n flag."
   exit 1
 fi
 
 if [ -z "${FLUX_DESCRIPTOR}" ] && [ ! -z "${EXPERIMENT}" ]; then
-  if ! nuis-flux ${EXPERIMENT} -m ${BEAM_MODE} -p ${PROBE} &> /dev/null; then
-    echo "[ERROR]: nuis flux could not find a flux descriptor for: Experiment: ${EXPERIMENT}, Probe: ${PROBE}, Beam Mode: ${BEAM_MODE}"
+  if ! nuis-flux ${EXPERIMENT} -M ${BEAM_MODE} -P ${PROBE} &> /dev/null; then
+    echo "[ERROR]: ${NUIS_BREADCRUMBS} -- nuis flux could not find a flux descriptor for: Experiment: ${EXPERIMENT}, Probe: ${PROBE}, Beam Mode: ${BEAM_MODE}"
     exit 1
   fi
-  FLUX_DESCRIPTOR=$(NUIS_CLID_DEBUG= nuis-flux ${EXPERIMENT} -m ${BEAM_MODE} -p ${PROBE})
+  FLUX_DESCRIPTOR=$(NUIS_CLID_DEBUG= nuis-flux ${EXPERIMENT} -M ${BEAM_MODE} -P ${PROBE})
 fi
 
 if [ -z "${FLUX_DESCRIPTOR}" ]; then
@@ -217,10 +269,24 @@ if [ -z "${FLUX_FILE}" ] || [ -z "${FLUX_HIST}" ]; then
   exit 1
 fi
 
-SEED=${RANDOM}
+if [ -z "${SEED}" ]; then
+  SEED=${RANDOM}
+fi
 
-NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
-  PROBE=${PROBE} \
+if [ -z "${OUTPUT_FILENAME}" ]; then
+  OUTPUT_FILENAME=${VERB}.${PROBE}.${FLUX_HIST}.${FLUX_FILE_NAME%%.root}.${SEED}.evts.root
+fi
+
+if [ -e "${OUTPUT_FILENAME}" ]; then
+   echo "[ERROR]: ${NUIS_BREADCRUMBS} -- Already have file: ${OUTPUT_FILENAME}, not overwriting."
+   exit 1
+fi
+
+if [ ! -z ${NUIS_CLID_DEBUG} ]; then
+
+echo "[INFO]: FORWARDED_ARGS: N = ${#FORWARDED_ARGS[@]}, ARGS=(${FORWARDED_ARGS[@]})"
+echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): " NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
+  PROBE=${PROBE} PROBE_PDG=${PROBE_PDG} \
   TARGET_NAME=${TARGET_NAME} \
   NEVENTS=${NEVENTS} \
   OUTPUT_FILENAME=${OUTPUT_FILENAME} \
@@ -230,4 +296,22 @@ NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
   FLUX_HIST=${FLUX_HIST} \
   FLUX_FILE_NAME=${FLUX_FILE_NAME} \
   FLUX_MeV=${FLUX_MeV} \
+  SEED=${SEED} \
+  QUIET=${QUIET} \
+  ${COMMAND}-${VERB} "${FORWARDED_ARGS[@]}"
+fi
+
+NUIS_BREADCRUMBS=${NUIS_BREADCRUMBS} \
+  PROBE=${PROBE} PROBE_PDG=${PROBE_PDG} \
+  TARGET_NAME=${TARGET_NAME} \
+  NEVENTS=${NEVENTS} \
+  OUTPUT_FILENAME=${OUTPUT_FILENAME} \
+  EXPERIMENT=${EXPERIMENT} \
+  BEAM_MODE=${BEAM_MODE} \
+  FLUX_FILE=${FLUX_FILE} \
+  FLUX_HIST=${FLUX_HIST} \
+  FLUX_FILE_NAME=${FLUX_FILE_NAME} \
+  FLUX_MeV=${FLUX_MeV} \
+  SEED=${SEED} \
+  QUIET=${QUIET} \
   ${COMMAND}-${VERB} "${FORWARDED_ARGS[@]}"
